[package]
name = "auth-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }

api = { package = "auth-api", version = "0.1", path = "../auth-api" }
setup = { version = "0.1", path = "../../pkg/setup" }

[features]
default = ["testutils"]
testutils = []
