# TODO: Run integration tests
name: Continuous Integration - Services

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # TODO: Discover services
        service:
          - auth
          - user
          - dummy

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Install workspace-cache
      uses: preiter93/workspace-cache/.github/actions/install-workspace-cache@main

    - name: Build
      uses: preiter93/workspace-cache/.github/actions/build-workspace@main
      with:
        binary: ${{ matrix.service }}
        working-directory: services
        profile: debug

    - name: Run tests
      working-directory: services
      env:
        CARGO_TARGET_DIR: .workspace-cache/target
      run: cargo test -p ${{ matrix.service }} --verbose

    - name: Clippy
      working-directory: services
      env:
        CARGO_TARGET_DIR: .workspace-cache/target
      run: cargo clippy -p ${{ matrix.service }} --workspace -- -D warnings
